import React from "react";

export function Privacy() {
  return (
    <>
      This restaurant privacy policy (the “Policy”) describes how OpenTable,
      Inc. and its subsidiaries (collectively, “OpenTable,” “we,” “our” or “us”)
      collect, use, process and share personal information from current or
      prospective restaurant customers, service providers and partners. This
      Policy applies to current and prospective restaurant customers, service
      providers, and partners who visit and/or use (individually, “you”)
      OpenTable’s websites, applications, social media accounts, and other
      online services (each, a “Site”, and collectively, our “Sites”). For
      particular types of information or processing, we may provide you with
      choices or request your additional consent related to what information we
      collect and how we may process it. Please note that your use of our Sites
      is additionally subject to the OpenTable Terms of Use where applicable in
      addition to any rights specified in your Client Agreement. Information We
      Collect and Use How We Use Your Information How We Share Your Information
      How We Store and Protect Your Information Cookies Your Choice and Rights
      International Transfers of Information Links to Other Websites Children
      Changes to This Policy How to Contact Us I. INFORMATION WE COLLECT AND USE
      When you use or visit our Site, we collect information directly from you
      (e.g., when you make selections on our platform). We may also generate
      information about you (e.g., information about your device when you use
      our mobile application). In some cases, we also obtain personal
      information from third parties (e.g., restaurants, business partners, our
      group companies, or other third parties). “Personal information” is data
      that identifies, relates to, describes, can be used to contact, or could
      reasonably be linked directly or indirectly to you. For purposes of this
      Policy, there is no meaningful distinction between the terms “personal
      information” and “personal data.” Personal Information We Collect Directly
      From You. Certain parts of our Site may ask you to provide personal
      information. For example, if you provide your contact details to register
      an account with us, subscribe to marketing communications (like our
      newsletters), or enable us to contact you. If you contact us to find out
      more about the OpenTable Services, we will collect personal information
      about you so that we can fulfill your request. We collect the following
      personal information from you, depending on the products and features you
      use: Personal details. Your name, contact information (e.g., email address
      and phone numbers) or address. Restaurant and Business Contact
      Information. The name of the organization or entity you represent, email
      address, postal address, or phone number. Restaurant Content. Your
      restaurant profile, restaurant photos, menus, and other similar materials
      you provide to us. Account Information. Your account settings or
      passwords. Your OpenTable Preferences. Your preferred in-product settings
      or account-specific configurations. Social Media Information. Links to
      your restaurant social media accounts. Communications You Send Us.
      Customer support inquiries or other requests you make through our Sites
      and Services. Other Information You May Provide. Information you provide
      about yourself or others through our Sites or Services, or to which you
      provide us with access via third-party platforms. You may choose not to
      provide some of the personal information described above. Please note,
      however, that our Sites may require some personal information to operate
      so if you choose not to provide the personal information necessary to
      operate and provide you with a particular Site feature, you may be unable
      to use that feature. We do not proactively collect sensitive personal
      information, such as health-related information. However, our Sites
      include text boxes that are designed for you to communicate with us and
      provide feedback you would like us to know. Please be aware that
      information you freely submit in these boxes may reveal to us or our
      affiliates with which we or they share information (as detailed below)
      certain information that may be considered sensitive personal information
      under applicable law. We do not use this information for the purpose of
      marketing or advertising products to you. Sensitive personal information
      you voluntarily submit is processed on the basis of your consent, which
      you may revoke at any time by contacting us at the details set out in the
      How to Contact Us section below. Personal Information Generated By Us. As
      you visit our Sites, we generate certain personal information about you,
      including through automatic data collection and by inferences based on the
      information we collect about you and your activity. We may automatically
      collect information about your interactions with the Site or
      communications you receive (such as email) using certain technologies,
      such as cookies, web beacons and other technologies (see our Cookies and
      Interest-Based Advertising Policy for more details). We generate the
      following categories of personal information about you: Device
      information. Device type (e.g., your mobile device, computer, or tablet),
      information about your hardware and software, device configuration, device
      operating systems, browsers, device identifiers (e.g., IP address, IMEI
      number, MAC address), and country of origin, region and language settings.
      Usage and performance information. We also automatically collect personal
      information about your usage of the Site, including information about your
      searches or interactions with features of our Site; sites or pages
      visited; booking path; access times. Location information. If you visit
      our Site, we automatically collect generic location information about you
      (such as city or neighborhood) or, with your consent, precise geographic
      location data from your mobile device when the app is running and when it
      is not running, depending on the choices you make when you are asked to
      consent to our collection of location information. Inferences about you.
      We combine the information we collect, generate, or otherwise obtain to
      draw inferences about your preferences and interests in order to provide
      and personalize our Sites and tailor the offers we and our partners
      provide to you. We may use and store this information to provide and
      improve features of our Sites, for example, to tailor our Site on a
      needs-based manner to better facilitate your requests and to provide you
      with more relevant content and features. Please see the Your Rights and
      Choices section below for more information about how to adjust your
      preferences, including those related to location information. Personal
      Information We Obtain from Third Parties. We may also receive certain
      categories of personal information from third parties, such as third-party
      websites, applications, social media networks, and services (which may
      include publicly-available sources; each of these is a “third-party
      platform”), our group companies, and other third parties. If you are a
      current OpenTable restaurant customer, we will combine this information
      with information we collect through our Services and use and share it for
      the purposes described below. The categories of personal information we
      may obtain from third parties include: Your name Email address or other
      contact information Social media data, if you connect to our Sites using a
      social media third-party platform, or if any of your social media data is
      available to the public, we may receive information from that social media
      third-party platform or a third-party service about those interactions and
      your profile Browsing, usage and advertising details, including how you
      use our Site and/or third-party websites, applications, and services, and
      information relating to your interactions with our advertising and
      marketing materials. Third parties may also collect, use, and share
      information about you (such as independent platforms you choose to use in
      connection with our Sites, e.g., payment processors). This Policy does not
      cover such third-party services or their use of personal information and
      we do not take responsibility for their privacy practices. For more
      information about the information we share with third parties and the
      recipients of such information, please refer to the How We Share Your
      Information section of this Policy. II. HOW WE USE YOUR INFORMATION We use
      your information to provide our Services, tailor your experience, send you
      marketing communications, improve our Site, improve our customer service
      and for other purposes described below. If you need to be informed of new
      actions by your restaurant diners (such as new bookings and transactions),
      we will use the information provided by you to communicate those events to
      you. We also provide the capacity for you to communicate with diners, such
      as notifying them of changes to their reservations. We use this
      information (alone or in combination with other information we have
      collected about you) for the following purposes (“Purposes”): Provide the
      Services, which includes providing you with the services, products, and
      functionality offered through our Services at your request. For our
      internal operations. To administer our Site and for internal operations,
      including troubleshooting, data analysis, testing, research, statistical
      and survey purposes. To improve our Site. To understand how our Site is
      used and to improve our Site to ensure that content is presented in the
      most effective manner for you and your computer. To keep our Site and your
      account secure. To authenticate your account credentials and identify you,
      as necessary to log you into the Services and as part of our efforts to
      keep our Site and your account secure. To communicate with you, about your
      account or use of the Services, products, and/or features; to respond to,
      or follow up on your comments and questions, and otherwise, to provide you
      with customer service. To provide you with relevant marketing, offers and
      services, including for the purposes of advertising and delivering more
      relevant content, including communicating with you about services or
      products offered by OpenTable, our group companies, or our business
      partners and other marketing communications that we believe you would be
      interested in, as permitted by law. To comply with and enforce applicable
      legal requirements, agreements, and policies, including government
      requests and to validate your identity when necessary. For fraud
      prevention and protection. To protect against, investigate, and deter
      fraudulent, unauthorized or illegal activity. For other purposes, as
      otherwise consented by you and as permitted by applicable laws. You have
      choices about your personal information, and in some circumstances, you
      may have the right to opt-out or object to our uses of your personal
      information for these Purposes. For more information, or to exercise these
      or other rights (where available), see the Your Choices and Rights section
      below. We may provide your information to our affiliates (meaning any
      subsidiary, parent company or company under common control with
      OpenTable). Our affiliates will use your information only for the purposes
      described in this Policy. When we process your personal information, we
      rely on the following legal bases: Performance of the contract we have
      with you (such as if you use our Services for restaurant reservation
      capabilities or table-management purposes, we will use your information to
      carry out our contractual obligation to provide you with our Services by
      sharing your information on our platform). Compliance with legal
      obligations to which we are subject (such as tax obligations, and when we
      are obliged to comply with lawful requests from competent authorities such
      as law enforcement). To serve our legitimate interests (such as tailoring
      your experience with our Sites or Services, carrying out online
      advertising, and for fraud detection), provided that such processing does
      not outweigh your rights and freedoms. The processing may also be pursuant
      to other applicable legal bases for data processing especially provisions
      set out under local law. Where we use personal information to meet our
      legitimate interests, we take steps to ensure that your rights with
      respect to your personal information are not infringed. You can contact us
      using the details set out in the How to Contact Us section below for more
      information about the steps we take to ensure these rights are not
      infringed. You also have the right to object to such processing as
      described in the Your Choices and Rights section below. Additional Grounds
      for Processing Consent. To the extent that a legal ground described above
      would not apply to processing of your personal information by us, we will
      seek your consent for such specific purposes in accordance with applicable
      law (such as sending direct marketing messages by electronic means, like
      email, without an exception from the requirement to obtain consent).
      Aggregate Information. We aggregate personal information collected
      directly from you, information generated about you by us, and information
      obtained from third parties (with your consent, where required) with
      personal information collected about other prospective or current
      restaurants in order to produce general statistics that cannot be linked
      to you or any other specific restaurant or restaurant user. Information
      that has been aggregated and de-identified is no longer considered
      “personal information” and may be subsequently used for any purpose in
      accordance with applicable laws. Anonymized Information. We may process
      information that cannot be linked to you or any other specific restaurant
      or restaurant user using any means available to us, either because it was
      collected anonymously or has been subsequently anonymized. Information
      that is anonymous or has been anonymized is no longer considered “personal
      information” and may be subsequently used for any purpose in accordance
      with applicable laws. III. HOW WE SHARE YOUR INFORMATION We disclose the
      personal information we collect (or otherwise generate or obtain) as
      follows: With your restaurant affiliates. We share your information with
      your restaurant affiliates for the restaurant or restaurant group’s own
      purposes, which may include marketing or advertising purposes. With our
      group companies. We share your information with our group companies,
      including but not limited to for the Purposes described above, to provide
      you with integrated products and services, and for our and their marketing
      purposes (see below for more detail on Sharing with Our Group Companies).
      With other business partners. We share information with other third-party
      business partners for their own marketing purposes, including sharing with
      online advertisers or advertising technology (“ad tech”) companies to
      provide you with targeted advertising and marketing communications, where
      permitted under law (see below for more detail on Sharing with Our
      Business Partners). With social networking services. We share (or
      facilitate your sharing of) your information with social networking
      services when you use our Sites or Services to connect and share your
      information publicly, or when you use our Sites or Services to connect
      with us on, share on, or use third-party social networking platforms and
      services (see below for more detail on Sharing with Social Networking
      Services). Third-party services or applications you use to log into your
      account. If you or your employees use a third-party service or application
      (e.g., Facebook) to log into your OpenTable account, we share certain
      personal information with that third party, such as your name and email
      address. With other service providers. We share information with
      third-party vendors, consultants, and other service providers who perform
      services or functions on our behalf (see below for more detail on Sharing
      with Other Service Providers). In the event of a corporate transaction. We
      may disclose or transfer your information to a third party if we sell,
      transfer, divest, or disclose all or a portion of our business or assets
      to another company in connection with or during negotiation of any merger,
      financing, acquisition, bankruptcy, dissolution, transaction, or
      proceeding. To protect rights and property. We may disclose your
      information to third parties when we believe in good faith that disclosure
      is necessary to protect our rights, our property, the integrity of the
      Services, personal safety, or the interests of you or any other person,
      and to detect, prevent and/or otherwise address fraud, risk management,
      security or technical issues. To comply with and as required by law. We
      may disclose your information to government authorities or other relevant
      third parties in order to comply with applicable legal requirements,
      judicial proceedings, court orders, legal process, or lawful requests from
      governmental authorities. Aggregate information. We share aggregate
      statistical data for the improvement of our Services. We may also share
      aggregate or de-identified information with third parties at our
      discretion. At your request. We also share your information as directed or
      requested by you, or subject to your consent. In some circumstances, you
      may have the right to opt-out or object to our sharing of your information
      with certain third parties. For more information, or to exercise these or
      other rights, see the Your Choices and Rights section below. Our Role as
      Data Controller and Data Processor. For purposes of European Union law,
      under certain OpenTable programs we provide to restaurants, restaurants
      may engage us to provide them with certain processing services related to
      information owned or controlled by the restaurant. In providing these
      services, we may share certain of your information with our affiliated
      brands, the restaurant’s affiliated restaurants (such as affiliated
      brands), restaurant group and/or restaurants with the same brand or
      parent-brand (collectively, such restaurant’s “restaurant group”), or
      other entities associated with the restaurant (such as the parent entity
      of the restaurant group or affiliated hotels) and/or their service
      providers (collectively, the associated entities and service providers,
      the restaurant’s “restaurant affiliates“) under OpenTable’s programs for
      the following purposes as permitted by applicable law, to perform
      analytics and tailor marketing to you. To learn more about your choices
      related to how we share your information with restaurant groups and
      restaurant affiliates under our programs, please see the Your Choices and
      Rights section below. Sharing with Our Group Companies. We share your
      information with our affiliates and subsidiaries in the U.S. and
      worldwide, as well as with our parent corporation, Booking Holdings Inc.,
      and its other subsidiaries (collectively, as also defined earlier in this
      Policy, “our group companies”). We may share your information with our
      group companies for the following reasons: Provide you with integrated
      services (including to administer and manage reservations, purchases,
      services, and payments across our affiliated platforms). Provide
      personalized offers or send you marketing communications with your consent
      or as otherwise permitted by applicable law. Enable “single sign-on”,
      i.e., allowing you to log into a shared account for multiple Booking
      Holdings Inc. brands using a single set of log-in credentials, which
      allows us to, for example, show your account details and preferences made
      through the websites, applications, and services of our group companies on
      your account page, and allows our group companies to show information in
      your respective account(s) with them. Provide customer support services.
      Detect, prevent, and investigate fraud and misuse of our services, other
      illegal activities, and data breaches. Analyze how restaurants or
      restaurant users use our independent and affiliated platforms, including
      so that we may improve existing products and services and develop new
      features, products, and services that may be of interest to our
      restaurants or restaurant users. Ensure compliance with applicable law. To
      learn more about your choices related to how we share your information
      with our group companies, please see the Your Choices and Rights section
      below. Sharing with Our Business Partners. We share your information with
      other third-party business partners for their own marketing purposes.
      These third parties include online advertisers or ad tech companies, who
      may provide you with targeted advertising and marketing communications,
      where permitted under law. The information we share includes information
      collected through your use of our Sites or Services and information we
      collect about you through the use of cookies and similar technologies. To
      learn more about your choices related to how we share your information
      with our business partners, please see the Your Choices and Rights section
      below. Sharing with Social Networking Services. Our Sites and Services
      allow you to connect and share your restaurant content and information
      publicly. Our Services may also allow you to connect your restaurant with
      us on, share on, and use third-party platforms, including those on which
      OpenTable has a presence. Please be mindful of your restaurant privacy
      needs and the privacy needs of others as you choose whom to connect with
      and what to share and make public. We cannot control the privacy or
      security of information you choose to make public or share with others.
      OpenTable also does not control the privacy practices of third-party
      platforms. Please contact those sites and services directly to learn about
      their privacy practices. Sharing with Other Service Providers. We share
      information with third-party vendors, consultants, and other service
      providers who perform services or functions on our behalf (e.g., hosting
      or operating our Services, data collection, reporting, ad response
      measurement, site analytics, data analysis, delivering marketing messages
      and advertisements, and providing fraud detection services). We do not
      authorize these third parties to use or disclose your information for
      purposes other than for which it has been provided. We require these third
      parties to maintain and implement security measures to protect your
      information from unauthorized access or processing. IV. HOW WE STORE AND
      PROTECT YOUR INFORMATION We maintain commercially-reasonable technical,
      administrative, and physical security measures designed to protect your
      information from loss, misuse, unauthorized access, disclosure,
      alteration, and destruction. Security safeguards. We use technical and
      organizational security measures designed to protect personal information
      we process about visitors to our Site against unauthorized access,
      disclosure, alteration and destruction. However, please note that no
      Internet transmission can ever be guaranteed 100 percent secure, and so we
      encourage you to take care when disclosing personal information online and
      to use readily available tools, such as Internet firewalls, secure email,
      and similar technologies to protect yourself online. Except to the extent
      that liability cannot be excluded or limited due to applicable law, we
      assume no liability or responsibility for disclosure of your information
      due to errors in transmission, unauthorized third-party access, or other
      causes beyond our control. You play an important role in keeping your
      information secure. You or your restaurant users should not share your
      user name, password, or other security information for your OpenTable
      account with anyone. If we receive instructions using your user name and
      password, we will assume you have authorized the instructions. If you have
      reason to believe that your interaction with us is no longer secure (e.g.,
      if you feel that the security of any account you might have with us has
      been compromised), please contact us immediately as detailed in the How to
      Contact Us section below. Retention. We may retain your or your restaurant
      users’ personal information for as long as your account is active and for
      a period of time thereafter to allow you to re-activate your account
      without loss of information. We may also retain your personal information
      as necessary to: Maintain logs and business records for analysis,
      security, and/or audit purposes Comply with record retention requirements
      under the law Deal with any complaints regarding the Services; and Comply
      with our legal obligations, protect or defend our rights, resolve disputes
      and enforce our contracts V. COOKIES When you or your restaurant users use
      or visit the Services, we collect information about your usage and
      activity using cookies, web beacons, and other technologies. Third parties
      may also view, edit, or set their own cookies. We and our third-party
      service providers, our group companies, and other business partners may
      also place web beacons for these third parties. The use of these
      technologies by third parties is subject to their own privacy policies and
      is not covered by this Policy, except as required by law. See our Cookies
      and Interest-Based Advertising Policy for more details. VI. YOUR CHOICES
      AND RIGHTS Email. If you no longer want to receive marketing and
      promotional emails from OpenTable, you may click on the “unsubscribe” link
      in such emails to opt-out of future marketing email communications. Please
      note that even if you opt-out of receiving marketing communications from
      one or all of our Services, we will still send you service-related
      communications. Cookies and Interest-Based Advertising. To exercise
      choices regarding cookies set through our websites or Services, as well as
      other types of online tracking and online advertising, see our Cookies and
      Interest-Based Advertising Policy for more details. We currently do not
      employ technology that recognizes “do-not-track” signals from your
      browser. Application Location. As explained in more detail in the
      Information We Collect and Use section above, we collect information about
      your location if you enable location services through the settings in your
      mobile device, or with your consent, as may be required by law. You can
      change the privacy settings of your device at any time to turn off the
      sharing of this location information with our Services. If you choose to
      turn off location services, this could affect certain features of our
      Services. If you have specific questions about the privacy settings of
      your device, we suggest you contact the manufacturer of your device or
      your mobile service provider for help. Legal Rights. In addition to any
      rights specified in your Client Agreement, where applicable under local
      law, you or your restaurant users may have the following rights regarding
      your personal information: the right to access personal information we
      hold, and in some situations, the right to have that personal information
      corrected or updated, erased, restricted, or delivered to you or a third
      party in a usable electronic format (the right to data portability). Where
      applicable, you may also object to how we use your personal information if
      the legal basis for processing that information is our legitimate
      interest. Where we are using your personal information on the basis of
      your consent, and where applicable under local law, you have the right to
      withdraw that consent at any time. Where you have granted consent to
      receive direct marketing communications from us, and where applicable
      under local law, you may withdraw that consent at any time. If you or your
      restaurant users wish to exercise legal rights you may have under
      applicable law, please submit your request to privacy@opentable.com. So
      that we can better process your request, please provide the email you use
      to log into your OpenTable account. If you do not have an OpenTable
      account, please provide the email and any other relevant contact
      information you used to make requests or to use our Services. Where
      applicable, you may also have the right to register a complaint to your
      local data protection authority. For residents of the EU and UK, contact
      information for the EU data protection authorities can be found at
      https://ec.europa.eu/justice/article-29/structure/data-protection-authorities/index_en.htm.
      For residents of Australia, if you are not satisfied with the outcome of
      your complaint after first contacting us, you may wish to contact the
      Office of the Australian Information Commissioner; for more information,
      please refer to http://www.oaic.gov.au. VII. INTERNATIONAL TRANSFERS OF
      INFORMATION Information about you or your restaurant users will be
      transferred to, or accessed by, entities located around the world as
      described in this Policy. Some of these entities may be located in
      countries (such as the United States) that do not provide an equivalent
      level of protection for personal information as your home country. We have
      put in place safeguards to provide adequate protection for transfers of
      certain information, in accordance with applicable legal requirements. For
      more information on the appropriate safeguards in place, or to request a
      copy of these safeguards, please contact us using the contact details
      listed in the How to Contact Us section below. VIII. LINKS TO OTHER
      WEBSITES Our Services contain links to other websites or services that are
      not owned or controlled by OpenTable, including links to websites of
      restaurants and restaurant affiliates and our advertisers, our group
      companies, and other business partners. This Policy only applies to
      information collected by our Services. We have no control over these third
      party websites, and your use of third party websites and features are
      subject to privacy policies posted on those websites. We are not
      responsible or liable for the privacy or business practices of any third
      party websites linked to our Services. Your use of third parties’ websites
      linked to our Services is at your own risk, so we encourage you to read
      the privacy policies of any linked third party websites when you leave one
      of our Services. IX. CHILDREN Our Sites and Services are not directed at
      or intended for use by children. We do not knowingly collect information
      from, children under 16 years of age. If you become aware that an
      individual under 16 years of age has provided us with information without
      your consent, please contact us at using the contact details listed in the
      How to Contact Us section below. X. CHANGES TO THIS POLICY Except to the
      extent limited by applicable law, we will update this Policy from time to
      time to reflect changes in our privacy practices, legal requirements, and
      other factors by prominently posting notice of the update on our Services.
      Changes to our Policy will be effective when posted and the new effective
      date will be identified. If we make any changes to the Policy that
      materially impact previously collected personal information about you, we
      will make reasonable efforts to provide notice and obtain consent to any
      such changes as may be required by law. To request a copy of this Policy,
      or to request a copy of the Policy in place at the time you signed up for
      an account, please contact us at the details below. XI. HOW TO CONTACT US
      If you have any questions about this Policy or the way in which your
      personal information has been used, please contact us by email at
      privacy@opentable.com or by postal mail at: OpenTable, Inc. 1 Montgomery
      St., Suite 700 San Francisco, CA 94104, U.S.A. Attention: Legal Department
      For California consumers, please find additional disclosures regarding
      this policy here.
    </>
  );
}
